### ISSUE TITLE
setup.m fails

### ISSUE THREAD

**Issue by mina0** [duqbo/optdmd#2]
Hello Sir,

The file setup.m fails. How to edit the compile flags in src/buildqrmex?

Does it require to install a compiler?

Is the elapsed time the only difference between the fast and the slow file?

Thank you.

**Comment by askhamwhat** [comment]
Hi,

In order to help: What kind of error message are you getting when you run setup.m? Also, for reference, what version of MATLAB and what operating system are you using?

The script should work with MATLAB's built in mex compiler. I don't think you would need to install anything additional.

Yes, the elapsed time and memory usage should be the only difference. The fast file uses the mex based routines to call the same LAPACK routine as the matlab built-in but in a more efficient way.

**Comment by askhamwhat** [comment]
The latest release no longer relies on the mex files.
