### ISSUE TITLE
convergence issue using predicted/actual improvement

### ISSUE THREAD

**Issue by klapo** [duqbo/optdmd#5]
I finished a conversion of optDMD to python and ran into an issue when testing it against large values of noise and especially when doing statistical bagging.

Namely, when the eigenvalues errors dramatically increase when only implementing the predicted/actual improvement for adjusting lambda. If the algorithm enters the "gradient descent-like" branch or stalls out, the eigenvalue errors are typically an order of magnitude smaller.

Is there an obvious reason for this (e.g., bad initial conditions) or not using the projected POD modes? Is this behavior expected? For the statistical bagging, I implemented a quick-and-dirty solution of not using ensemble draws that terminate in this algorithm state. But, this issue also exists when using optDMD on very noisy data.

I have a .mlx script demonstrating the issue here: https://github.com/klapo/pyoptDMD/blob/main/examples/BOP_DMD_noisy_data_debugging.mlx

and an ipython notebook exploring the issue in the python implementation:
https://github.com/klapo/pyoptDMD/blob/main/examples/BOP-DMD.debug-noisy-data.ipynb

**Comment by askhamwhat** [comment]
Hello @klapo,
Thank you for bringing this to my attention and apologies for my slow response. 
This sounds like undesirable behavior. I think I know where this goes wrong. I'll take a stab at it and report back.
Cheers,
Travis

**Comment by askhamwhat** [comment]
Hello @klapo,
While I think that the algorithm has some non-optimal control flow (for instance, it was originally possible that a stall could be detected before increasing lambda was tried), it seems that this is indeed the expected behavior. 

The simple_example.m file has spatial modes which are correlated, especially when sampled on [0,1]. In particular, the condition number of the matrix [f1;f2;f3] is about 125 (with f1 and f3 being the most aligned, which actually explains why there is often an eigenvalue near -2 in the results and the other two eigenvalues give nonsense). Thus, at a high enough noise it is extremely hard to find the dynamics. I explored some of the noise instances (of size sigma=0.1) where you get very strange eigenvalues for that data. Trying many initial conditions, it seems that the global minimizers were indeed strange. Thus, I think it is not typically a failure of the optimization algorithm but a failure of the model (I also suspect that the POD orthogonalization might help a little with this in terms of outliers but won't completely fix it).. On the easier problem where you sample f1,f2,f3 on [0,pi] instead of [0,1], the eigenvalue recovery is much better (including for noise of size 0.1).

**Comment by klapo** [comment]
Hello @askhamwhat,
Thank you for the deep dive into the algorithm. This makes sense -- I just tried some variations of the simple example, including changing the x domain, and got _much_ more reasonable results even for very large sigma (see figures).

I just started implementing the [pydmd version of the optdmd ](https://github.com/mathLab/PyDMD/pull/308). Optdmd can be accessed by setting the bopdmd keyword `trials= 0`. It has the POD orthogonalization on by default, but didn't seem to make much (any?) difference.

Thanks again for taking a look at the sampler! I'll close the issue.

![image](https://user-images.githubusercontent.com/6980561/216937071-9f8e8353-76c4-4ade-8d18-875a1ffbe613.png)
![image](https://user-images.githubusercontent.com/6980561/216937236-22b57633-88a9-4a61-87af-2845c800c2f4.png)
